resources:
- ../../base

namespace: api

namePrefix: dev-

commonLabels:
  env: dev

patches:
- path: patchDeployment.yml
- path: patchIngress.yml
- path: patchService.yml
- path: patchHpa.yml
- path: patchJob.yml