apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
spec:
  replicas: 1
  template:
    metadata:
      name: api-server
    spec:
      containers:
        - name: api-server
          image: api-exam:0.0.2
          ports:
            - containerPort: 8080
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: dev
  restartPolicy: OnFailure
